project_name: nginx-build
env:
  - GO111MODULE=on
builds:
  - binary: nginx-build
    ldflags:
      - -s -w
      - -X main.NginxBuildVersion={{.Version}}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Version }}'
release:
  prerelease: auto
